# Generated by Django 5.0.2 on 2024-02-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_classschedule_course_classschedule_facilitator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='meeting_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
