# Generated by Django 5.0.1 on 2024-02-28 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_imuser_middle_name_imuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imuser',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cohortmember',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cohortmember',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort', to='users.cohort'),
        ),
        migrations.AlterField(
            model_name='cohortmember',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cohortmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imuser',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imuser',
            name='user_type',
            field=models.CharField(choices=[('EIT', 'EIT'), ('TEACHING_FELLOW', 'TEACHING FELLOW'), ('ADMIN_STAFF', 'ADMINISTRATIVE STAFF'), ('ADMIN', 'ADMINSTRATOR')], default='EIT', max_length=20),
        ),
    ]
