# Generated by Django 5.0.1 on 2024-03-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_imuser_date_modified_alter_cohort_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imuser',
            name='unique_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
